export const STAGE_CSS = `
.heroine-settings-control{box-sizing:border-box;width:100%;height:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;padding:0 10px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-1);font:inherit;font-size:14px;line-height:22px}.heroine-settings-control:focus{border-color:var(--dsw-alias-brand-primary);outline:none}.heroine-settings-control:disabled{cursor:default;opacity:.6}.heroine-menu-root{justify-self:end;min-width:0}.heroine-menu-root-full{justify-self:stretch}.heroine-menu-select{box-sizing:border-box;max-width:100%;height:36px;border:none;border-radius:18px;padding:0 14px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-module-platform);font:inherit;font-size:14px;line-height:22px;cursor:pointer;display:inline-flex;align-items:center;gap:12px}.heroine-menu-select:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.heroine-menu-select:disabled{cursor:default;opacity:.6}.heroine-menu-select-label{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.heroine-menu-select-chevron{flex:none}.heroine-settings-section{display:grid;gap:14px;margin-top:18px;padding:18px;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 62%,transparent)}.heroine-settings-section h3{margin:0;color:var(--dsw-alias-label-primary);font-size:14px}.heroine-settings-fields,.heroine-settings-nested{display:grid;gap:14px}.heroine-settings-nested{padding-top:14px;border-top:1px solid var(--dsw-alias-border-l1)}.heroine-settings-row{display:grid;grid-template-columns:minmax(170px,.7fr) minmax(240px,1.3fr);gap:14px;align-items:center}.heroine-settings-row strong,.heroine-settings-feature-head strong{display:block;font-size:13px}.heroine-settings-row small,.heroine-settings-feature-head small{display:block;color:var(--dsw-alias-label-tertiary);line-height:1.45}.heroine-settings-feature-head{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:16px}.heroine-settings-voices-status{display:flex;align-items:center;gap:10px;color:var(--dsw-alias-label-tertiary);font-size:12px}.heroine-settings-voices-status[data-error]{color:var(--dsw-alias-state-error-primary)}.heroine-settings-voices-status button{box-sizing:border-box;height:28px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;padding:0 10px;color:var(--dsw-alias-label-primary);background:transparent;font:inherit;cursor:pointer}.heroine-settings-voices-status button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.heroine-settings-voices-status button:disabled{cursor:default;opacity:.5}
.heroine-stage{position:relative;width:100%;height:100%;min-height:440px;overflow:hidden;color:var(--dsw-alias-label-primary);background:var(--heroine-bg,var(--dsw-alias-bg-base));isolation:isolate}
.heroine-stage::before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 35%,color-mix(in srgb,var(--dsw-alias-state-business-primary) 9%,transparent),transparent 48%);pointer-events:none;z-index:1}
.heroine-canvas-wrap{position:absolute;inset:0 0 126px;z-index:0;min-height:0}
.heroine-canvas{display:block;width:100%;height:100%}
.heroine-toolbar{position:absolute;top:50%;left:18px;z-index:4;display:flex;flex-direction:column;align-items:stretch;gap:3px;box-sizing:border-box;width:148px;padding:6px;border:1px solid color-mix(in srgb,var(--dsw-alias-border-l2) 76%,transparent);border-radius:16px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 78%,transparent);box-shadow:0 14px 38px color-mix(in srgb,#000 16%,transparent);backdrop-filter:blur(20px);transform:translateY(-50%)}
.heroine-tool-button{display:flex;align-items:center;gap:8px;box-sizing:border-box;width:100%;height:34px;padding:0 9px;border:0;border-radius:10px;color:var(--dsw-alias-label-secondary);background:transparent;font:inherit;font-size:13px;cursor:pointer}.heroine-tool-button:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}.heroine-tool-button[aria-pressed="true"]{color:var(--dsw-alias-state-business-primary);background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 12%,transparent)}.heroine-tool-state{margin-left:auto;min-width:20px;padding:1px 5px;border-radius:999px;color:var(--dsw-alias-label-tertiary);background:var(--dsw-alias-bg-layer-3);font-size:10px;text-align:center}.heroine-tool-button[aria-pressed="true"] .heroine-tool-state{color:var(--dsw-alias-state-business-primary);background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 14%,transparent)}
.heroine-scale-control{display:grid;grid-template-columns:30px 1fr 30px;align-items:center;height:34px;margin:2px 0;padding:2px;border-radius:10px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-3) 72%,transparent)}.heroine-scale-control button{display:grid;place-items:center;width:30px;height:30px;padding:0;border:0;border-radius:8px;color:var(--dsw-alias-label-secondary);background:transparent;cursor:pointer}.heroine-scale-control button:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}.heroine-scale-control button span{font-size:19px;line-height:1}.heroine-scale-control output{color:var(--dsw-alias-label-tertiary);font-size:10px;font-variant-numeric:tabular-nums;text-align:center}
.heroine-prompt-consent{position:absolute;z-index:8;top:50%;left:50%;display:grid;gap:10px;width:min(440px,calc(100% - 36px));box-sizing:border-box;padding:20px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-2);box-shadow:0 22px 70px rgba(0,0,0,.28);transform:translate(-50%,-50%);backdrop-filter:blur(18px)}.heroine-prompt-consent p{margin:0;color:var(--dsw-alias-label-secondary);line-height:1.55}.heroine-prompt-consent small{color:var(--dsw-alias-label-tertiary);line-height:1.45}.heroine-prompt-consent>div{display:flex;justify-content:flex-end;gap:8px;margin-top:4px}.heroine-prompt-consent button{padding:7px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-3);cursor:pointer}.heroine-prompt-consent button:first-child{border-color:var(--dsw-alias-state-business-primary)}
.heroine-status{position:absolute;top:18px;left:18px;z-index:4;padding:7px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;color:var(--dsw-alias-label-secondary);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 84%,transparent);backdrop-filter:blur(12px);font-size:12px}
.heroine-lower-dock{position:absolute;right:clamp(16px,4vw,52px);bottom:148px;left:clamp(16px,4vw,52px);z-index:4;display:flex;flex-direction:column;align-items:stretch;gap:10px;margin:auto;max-width:760px;pointer-events:none}.heroine-lower-dock>*{pointer-events:auto}
.heroine-dialogue{position:relative;box-sizing:border-box;width:100%;max-height:min(30vh,230px);padding:16px 20px;border:1px solid color-mix(in srgb,var(--dsw-alias-state-business-primary) 24%,var(--dsw-alias-border-l2));border-radius:16px;color:var(--dsw-alias-label-primary);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 91%,transparent);box-shadow:0 18px 48px color-mix(in srgb,var(--dsw-alias-label-primary) 11%,transparent);backdrop-filter:blur(18px)}
.heroine-name{margin-bottom:7px;color:var(--dsw-alias-state-business-primary);font-size:13px;font-weight:700;letter-spacing:.06em}
.heroine-line{max-height:min(22vh,155px);overflow:auto;font-size:clamp(15px,1.45vw,19px);line-height:1.65;white-space:pre-wrap;scrollbar-width:thin}
.heroine-thinking-dots{display:inline-flex;gap:4px;margin-left:7px;vertical-align:middle}
.heroine-thinking-dots i{width:5px;height:5px;border-radius:50%;background:currentColor;opacity:.24;animation:heroine-thinking-dot 1.15s ease-in-out infinite}
.heroine-thinking-dots i:nth-child(2){animation-delay:.16s}.heroine-thinking-dots i:nth-child(3){animation-delay:.32s}
@keyframes heroine-thinking-dot{0%,70%,100%{opacity:.24;transform:translateY(0)}35%{opacity:.9;transform:translateY(-3px)}}
.heroine-voice-hud{position:relative;display:flex;align-items:center;gap:9px;box-sizing:border-box;width:100%;min-width:0;padding:9px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;color:var(--dsw-alias-label-secondary);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 90%,transparent);box-shadow:0 12px 36px color-mix(in srgb,#000 12%,transparent);backdrop-filter:blur(14px);font-size:12px}
.heroine-input-mode-button{flex:0 0 auto;height:32px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;color:var(--dsw-alias-label-secondary);background:transparent;cursor:pointer}.heroine-input-mode-button:hover{color:var(--dsw-alias-label-primary);background:var(--dsw-alias-interactive-bg-hover)}.heroine-input-mode-button[aria-pressed="true"]{border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-state-business-primary)}
.heroine-mic-button,.heroine-voice-stop{flex:0 0 auto;padding:8px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-3);cursor:pointer}.heroine-mic-button{display:flex;align-items:center;gap:7px}.heroine-mic-button span{color:var(--dsw-alias-state-business-primary);font-size:12px}.heroine-mic-button[data-recording] span{color:var(--dsw-alias-state-error-primary);animation:heroine-recording-pulse 1s ease-in-out infinite}.heroine-mic-button:disabled{cursor:not-allowed;opacity:.5}.heroine-voice-stop{padding:7px 10px}.heroine-voice-error{color:var(--dsw-alias-state-error-primary)}
.heroine-audio-settings{position:relative;margin-left:auto;flex:0 0 auto}.heroine-audio-settings summary{list-style:none;padding:7px 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-3);cursor:pointer}.heroine-audio-settings summary::-webkit-details-marker{display:none}.heroine-audio-settings[open] summary{border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-label-primary)}
.heroine-audio-settings-panel{position:absolute;right:0;bottom:calc(100% + 12px);display:grid;gap:12px;box-sizing:border-box;width:min(360px,calc(100vw - 44px));padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-2);box-shadow:0 18px 48px color-mix(in srgb,#000 20%,transparent);backdrop-filter:blur(18px)}.heroine-audio-settings-panel label{display:grid;grid-template-columns:72px minmax(0,1fr) auto;align-items:center;gap:9px}.heroine-audio-input-select{grid-column:2/4;width:100%;justify-content:space-between}.heroine-audio-settings-panel input[type="range"]{width:100%;accent-color:var(--dsw-alias-state-business-primary)}.heroine-audio-settings-panel output{min-width:36px;color:var(--dsw-alias-label-primary);font-variant-numeric:tabular-nums}.heroine-audio-settings-panel small{color:var(--dsw-alias-label-tertiary);line-height:1.45}
.heroine-audio-meter-row{display:grid;grid-template-columns:72px minmax(0,1fr);align-items:center;gap:9px}.heroine-audio-meter{position:relative;height:8px;overflow:hidden;border-radius:999px;background:var(--dsw-alias-bg-layer-3)}.heroine-audio-meter i{position:absolute;inset:0 auto 0 0;width:var(--heroine-input-level);border-radius:inherit;background:var(--dsw-alias-state-business-primary);transition:width .08s linear}.heroine-audio-meter b{position:absolute;top:-2px;bottom:-2px;left:var(--heroine-vad-level);width:2px;border-radius:2px;background:var(--dsw-alias-state-warning-primary,#d98b16);transform:translateX(-1px)}
@keyframes heroine-recording-pulse{50%{opacity:.35;transform:scale(.78)}}
@media (max-width:620px){.heroine-settings-root{box-sizing:border-box;width:100%;overflow-x:hidden}.heroine-settings-row{grid-template-columns:minmax(0,1fr)!important;gap:6px!important}.heroine-settings-row>.heroine-menu-root,.heroine-settings-row>.heroine-settings-control{width:100%;justify-self:stretch}.heroine-settings-row small{line-height:1.4}}
.heroine-error{position:absolute;left:50%;top:50%;z-index:5;transform:translate(-50%,-50%);max-width:520px;padding:14px 18px;border:1px solid var(--dsw-alias-state-error-primary);border-radius:12px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-state-error-primary);text-align:center}
.heroine-pet{position:fixed;z-index:30;width:var(--heroine-pet-width,240px);height:var(--heroine-pet-height,333px);pointer-events:auto;touch-action:none;cursor:grab;filter:drop-shadow(0 16px 20px color-mix(in srgb,#000 28%,transparent));user-select:none}
.heroine-pet:active{cursor:grabbing}.heroine-pet-canvas{display:block;width:100%;height:100%}.heroine-pet-controls{position:absolute;top:0;right:0;z-index:2;display:flex;gap:4px;opacity:0;transition:opacity .15s}.heroine-pet:hover .heroine-pet-controls,.heroine-pet-controls:focus-within{opacity:1}.heroine-pet-controls button{display:grid;place-items:center;box-sizing:border-box;width:27px;height:27px;padding:0;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;color:var(--dsw-alias-label-secondary);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 88%,transparent);backdrop-filter:blur(10px);cursor:pointer}.heroine-pet-controls button:hover:not(:disabled){border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-label-primary)}.heroine-pet-controls button:disabled{cursor:default;opacity:.4}.heroine-pet-name{position:absolute;right:20px;bottom:2px;left:20px;padding:5px 8px;border:1px solid var(--dsw-alias-border-l1);border-radius:999px;color:var(--dsw-alias-label-secondary);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 76%,transparent);font-size:11px;text-align:center;backdrop-filter:blur(10px)}
.heroine-pet-mode{display:grid;place-items:center;background:var(--heroine-bg,var(--dsw-alias-bg-base))}.heroine-pet-mode-card{display:grid;justify-items:center;gap:10px;width:min(420px,calc(100% - 48px));padding:30px;border:1px solid var(--dsw-alias-border-l1);border-radius:20px;background:var(--dsw-alias-bg-layer-2);box-shadow:0 18px 50px color-mix(in srgb,#000 10%,transparent);text-align:center}.heroine-pet-mode-card span{color:var(--dsw-alias-label-tertiary);font-size:11px;letter-spacing:.12em}.heroine-pet-mode-card strong{color:var(--dsw-alias-label-primary);font-size:20px}.heroine-pet-mode-card p{max-width:340px;margin:0;color:var(--dsw-alias-label-secondary);font-size:13px;line-height:1.65}.heroine-pet-mode-card button{margin-top:4px;padding:9px 18px;border:1px solid var(--dsw-alias-state-business-primary);border-radius:10px;color:var(--dsw-alias-label-primary);background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 14%,var(--dsw-alias-bg-layer-2));cursor:pointer}
.heroine-dev-toggle{margin-left:2px;border-left:1px solid var(--dsw-alias-border-l2)}
.heroine-dev-panel{position:absolute;top:64px;right:16px;z-index:8;box-sizing:border-box;width:min(390px,calc(100% - 32px));max-height:calc(100% - 226px);overflow:auto;padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:16px;color:var(--dsw-alias-label-primary);background:color-mix(in srgb,var(--dsw-alias-bg-layer-2) 94%,transparent);box-shadow:0 22px 60px color-mix(in srgb,#000 24%,transparent);backdrop-filter:blur(22px);scrollbar-width:thin}
.heroine-dev-panel header{display:flex;align-items:baseline;justify-content:space-between;gap:12px;padding-bottom:10px;border-bottom:1px solid var(--dsw-alias-border-l1)}.heroine-dev-panel header span{color:var(--dsw-alias-label-tertiary);font-size:11px}.heroine-dev-panel section{display:grid;gap:8px;padding:11px 0;border-bottom:1px solid var(--dsw-alias-border-l1)}.heroine-dev-panel section:last-child{border-bottom:0}.heroine-dev-panel h4{margin:0;color:var(--dsw-alias-label-secondary);font-size:11px;letter-spacing:.08em}.heroine-dev-panel label{display:grid;grid-template-columns:58px 46px 1fr;align-items:center;gap:8px;color:var(--dsw-alias-label-secondary);font-size:12px}.heroine-dev-panel output{text-align:right;font-variant-numeric:tabular-nums}.heroine-dev-panel input[type="range"]{width:100%;accent-color:var(--dsw-alias-state-business-primary)}.heroine-dev-panel select{width:100%;padding:7px 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;color:var(--dsw-alias-label-primary);background:var(--dsw-alias-bg-layer-3)}
.heroine-dev-tip{margin:9px 0 0;color:var(--dsw-alias-label-tertiary);font-size:11px;line-height:1.45}
.heroine-dev-buttons{display:flex;flex-wrap:wrap;gap:6px}.heroine-dev-buttons button,.heroine-dev-reset{padding:6px 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;color:var(--dsw-alias-label-secondary);background:var(--dsw-alias-bg-layer-3);cursor:pointer;font-size:11px}.heroine-dev-buttons button:hover,.heroine-dev-reset:hover{border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-label-primary)}.heroine-dev-motion-list{max-height:142px;overflow:auto}.heroine-dev-reset{justify-self:start;margin-top:2px}
.heroine-thinking-presets{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.heroine-thinking-presets button{text-align:left}.heroine-thinking-presets button[aria-pressed="true"]{border-color:var(--dsw-alias-state-business-primary);color:var(--dsw-alias-label-primary-foreground);background:var(--dsw-alias-state-business-primary)}
.heroine-dev-note{margin-left:6px;color:var(--dsw-alias-label-tertiary);font-weight:400;letter-spacing:0}.heroine-dev-motion-list{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));max-height:190px}.heroine-dev-motion-list button{display:flex;align-items:center;justify-content:space-between;gap:5px;min-width:0;text-align:left}.heroine-dev-motion-list button span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.heroine-dev-motion-list button small{color:var(--dsw-alias-label-tertiary);font-size:9px;font-variant-numeric:tabular-nums}
@media(max-width:700px){.heroine-stage{min-height:380px}.heroine-lower-dock{right:10px;bottom:138px;left:10px}.heroine-dialogue{max-height:24vh;padding:13px 15px}.heroine-toolbar{top:52px;right:10px;left:10px;flex-direction:row;width:auto;overflow-x:auto;transform:none}.heroine-tool-button{width:auto;flex:0 0 auto}.heroine-scale-control{flex:0 0 104px}.heroine-status{top:12px;left:10px}.heroine-voice-hud{flex-wrap:wrap}.heroine-voice-hud>span{flex:1;min-width:150px}.heroine-audio-settings{margin-left:0}}
`
